### ISSUE TITLE
Airport control security

### ISSUE THREAD

**Issue by Jbbbb777** [Enchufa2/simmer#289]
I am trying to do a security check in an airport and i am meant to use a poisson distribuition instead of a exponential. Also i have 22 counters which it has a singular queue or one queue for each counter. The plots are not great so i may have some errors.
Security time consists in preparation time plus scanning time.
It is supposed to be an 1 hour simulation.

This is the code

env <- simmer("airport")
env 
lambda = 1384/60
 
passenger <- trajectory("passenger path") %>%
    log_("Arrived") %>% 
  seize("validation machine", 1) %>%
  timeout(function() runif(1,.016,.05 )) %>%
  release("validation machine", 1) %>%
    log_("Validated") %>%

  seize("counter") %>%
  timeout(function() rexp(1, lambda)) %>% 
  release("counter") %>%
  log_("arrived security") %>%
  
  seize("security time",1) %>%
  timeout(function() rtri(1,min= .17 ,max= .75, mode= .33)) %>%
  release("security time", 1) %>%
    log_("Vou-me embora(security time)") 

env %>% 
  add_resource("validation machine", 3) %>%
  add_resource("counter", 22) %>%
  add_resource("security time",1) %>% 
  add_generator("passenger", passenger, function() rexp(1 , lambda ))
    
env %>% run(until= 60)

**Comment by Enchufa2** [comment]
Closing this in favour of #290
